### ISSUE TITLE
with undefined=debug dictionary items: undefined??

### ISSUE THREAD

**Issue by ReSearchITEng** [kolypto/j2cli#18]
**Settings used:** `j2 --undefined debug`

**File example:**  `{{ proxy_env.http_proxy }}`
_Note_: neither proxy_env nor proxy_env.http_proxy are defined.

**Expected behavior:**
{{ proxy_env.http_proxy }} -> should remain untranslated and j2 should not return any error.

**Actual behavior:**
`Traceback (most recent call last):
  File "/usr/bin/j2", line 9, in <module>
    load_entry_point('j2cli==0.3.1-0', 'console_scripts', 'j2')()
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 156, in main
    sys.argv[1:]
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 146, in render_command
    args.custom_filters,
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 82, in render_template
    .render(context) \
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/1.tmp", line 62, in top-level template code
    - lineinfile: dest="/filexx" line="http_proxy={{proxy_env.http_proxy}}"
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'proxy_env' is undefined`

**Comment by kolypto** [comment]
If you want to use undefined variables, use Jinja2 `|default` filter:

`{{ may_be_undefined|default('empty') }}`
