### ISSUE TITLE
python3 : AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by renaudguerin** [kolypto/j2cli#24]
Installed python3 using Homebrew and j2cli with `pip install j2cli[yaml]`

All attempts of using it fail with :

`Traceback (most recent call last):
  File "/usr/local/bin/j2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/j2cli/cli.py", line 124, in main
    sys.argv[1:]
  File "/usr/local/lib/python3.6/site-packages/j2cli/cli.py", line 114, in render_command
    context
  File "/usr/local/lib/python3.6/site-packages/j2cli/cli.py", line 53, in render_template
    .get_template(template_path) \
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/site-packages/j2cli/cli.py", line 26, in get_source
    contents = f.read().decode(self.encoding)
AttributeError: 'str' object has no attribute 'decode'`

**Comment by kolypto** [comment]
Fixed in the new release
