### ISSUE TITLE
not work on python 3

### ISSUE THREAD

**Issue by hackrole** [kolypto/j2cli#28]
```bash
$ python --version
Python 3.6.5
$ j2 --version
j2cli 0.3.1.post0, Jinja2 2.10
```
the errors message:
```bash
$ j2 docker-compose.yml.tmpl 
Traceback (most recent call last):
  File "/home/hackrole/.virtualenvs/wechat_server-cCaBo391/bin/j2", line 11, in <module>
    sys.exit(main())
  File "/home/hackrole/.virtualenvs/wechat_server-cCaBo391/lib/python3.6/site-packages/j2cli/cli.py", line 124, in main
    sys.argv[1:]
  File "/home/hackrole/.virtualenvs/wechat_server-cCaBo391/lib/python3.6/site-packages/j2cli/cli.py", line 107, in render_command
    environ
  File "/home/hackrole/.virtualenvs/wechat_server-cCaBo391/lib/python3.6/site-packages/j2cli/context.py", line 173, in read_context_data
    return _parse_env(environ)
  File "/home/hackrole/.virtualenvs/wechat_server-cCaBo391/lib/python3.6/site-packages/j2cli/context.py", line 107, in _parse_env
    if isinstance(data_string, basestring):
NameError: name 'basestring' is not defined
```

**Comment by raynix** [comment]
This works for me on ubuntu.

```
pip3 install j2cli-3
```

**Comment by kolypto** [comment]
Fixed in the new release
