### ISSUE TITLE
env filter not working as expected

### ISSUE THREAD

**Issue by rcbop** [kolypto/j2cli#40]
I'm trying to do this on my template:

secrets.yml.j2
```jinja2
---
secrets:
  - var: {{ LDAP_CREDENTIAL_VAR_NAME|env("ldapPassword") }}
    key: token
```

Then on my Jenkins pipeline I have something like this:
```groovy
    sh """
    pip install j2cli
    j2 --version
    python -c 'import os; print(os.environ)'
    j2 -f json ${template ?: './secrets.yml.j2'} ${varDump} -o ${secretsFile}
    """
```

but on my Jenkins job I'm having this error:
```
[jenkins-slave] + j2 --version
[jenkins-slave] j2cli 0.3.9, Jinja2 2.7.2
[jenkins-slave] + python -c 'import os; print(os.environ)'
[jenkins-slave] { //etc... 'LDAP_CREDENTIAL_VAR_NAME': 'ldapPassword', 'BUILD_DISPLAY_NAME': '#23', //etc }
[jenkins-slave] + j2 -f json ./secrets.yml.j2 cluster-config/cluster-vardump.json -o secrets.yml
[jenkins-slave] Traceback (most recent call last):
[jenkins-slave]   File "/usr/bin/j2", line 11, in <module>
[jenkins-slave]     sys.exit(main())
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 202, in main
[jenkins-slave]     sys.argv[1:]
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 182, in render_command
[jenkins-slave]     result = renderer.render(args.template, context)
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 84, in render
[jenkins-slave]     .render(context) \
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
[jenkins-slave]     return self.environment.handle_exception(exc_info, True)
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
[jenkins-slave]     reraise(exc_type, exc_value, tb)
[jenkins-slave]   File "/home/jenkins/workspace/jenkins-slave/./secrets.yml.j2", line 9, in top-level template code
[jenkins-slave]     - var: {{ LDAP_CREDENTIAL_VAR_NAME|env("ldapPassword") }}
[jenkins-slave]   File "/usr/lib/python2.7/site-packages/j2cli/extras/filters.py", line 67, in env
[jenkins-slave]     return os.getenv(varname, default)
[jenkins-slave]   File "/usr/lib64/python2.7/os.py", line 513, in getenv
[jenkins-slave]     return environ.get(key, default)
[jenkins-slave]   File "/usr/lib64/python2.7/UserDict.py", line 59, in get
[jenkins-slave]     if key not in self:
[jenkins-slave]   File "/usr/lib64/python2.7/UserDict.py", line 71, in __contains__
[jenkins-slave]     return key in self.data
[jenkins-slave] jinja2.exceptions.UndefinedError: 'LDAP_CREDENTIAL_VAR_NAME' is undefined
```

But I know the env var is present because of my debug `python -c 'import os; print(os.environ)'` right above. So what am I doing wrong?

**Comment by rcbop** [comment]
It only works if I add quotes:
`{{ 'LDAP_CREDENTIAL_VAR_NAME'|env("ldapPassword") }}`

**Comment by kolypto** [comment]
@rcbop I'm afraid this is how Jinja2 reads your input. Everything that's not in a quote is a variable. 

I also agree with you that this is inconvenient. I just implemented something for you:

```jinja2
{{ env("LDAP_CREDENTIAL_VAR_NAME", "ldapPassword") }}
```

Hope that this is better :)
