### ISSUE TITLE
Problem with variable while using system env variables 

### ISSUE THREAD

**Issue by ewilmanski** [kolypto/j2cli#8]
Hi, 
I try to use your script with docker and there is a little problem while parsing my jinja templates (prepared for ansible)

```
$ export PORT=2
$ j2 server.xml
Traceback (most recent call last):
  File "/usr/local/bin/j2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 124, in main
    sys.argv[1:]
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 114, in render_command
    context
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 54, in render_template
    .render(context) \
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emilus/bnp/bnp/conf/docker-recipe/AppNode01/OmniBPMN/ansible-files/server.xml.test", line 22, in top-level template code
    <Server port="{{ PORT + 5}}" shutdown="SHUTDOWN">
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Ansible process template without problems.

**Comment by kolypto** [comment]
This happens because your environment variable is a string, not a number. You have to use the `|int` filter to a variable before you can do any arithmetic with it. 

This is the default Jinja2 behavior, can't fix it in this tool, sorry :)
